// Subscription Events
export const SubscriptionEventTypes = {
  DUMMY: 'DUMMY',
  SPACE_UPDATED: 'SPACE_UPDATED',
  STYLE_UPDATED: 'STYLE_UPDATED',
  // Space
  SPACE_ADD_PAGE: 'SPACE_ADD_PAGE',
  SPACE_UPDATE_PAGE: 'SPACE_UPDATE_PAGE',
  SPACE_SET_HOME_PAGE: 'SPACE_SET_HOME_PAGE',
  SPACE_REMOVE_PAGE: 'SPACE_REMOVE_PAGE',
  SPACE_ADD_PAGE_FOLDER: 'SPACE_ADD_PAGE_FOLDER',
  SPACE_UPDATE_PAGE_FOLDER: 'SPACE_UPDATE_PAGE_FOLDER',
  SPACE_REMOVE_PAGE_FOLDER: 'SPACE_REMOVE_PAGE_FOLDER',
  SPACE_ADD_VARIABLE: 'SPACE_ADD_VARIABLE',
  SPACE_UPDATE_VARIABLE: 'SPACE_UPDATE_VARIABLE',
  SPACE_REMOVE_VARIABLE: 'SPACE_REMOVE_VARIABLE',
  SPACE_ADD_ELEMENT: 'SPACE_ADD_ELEMENT',
  SPACE_UPDATE_ELEMENT: 'SPACE_UPDATE_ELEMENT',
  SPACE_REMOVE_ELEMENT: 'SPACE_REMOVE_ELEMENT',
  SPACE_MOVE_ELEMENT: 'SPACE_MOVE_ELEMENT',
  SPACE_CLONE_ELEMENT: 'SPACE_CLONE_ELEMENT',
  SPACE_ADD_TEMPLATE: 'SPACE_ADD_TEMPLATE',
  SPACE_UPDATE_SETTINGS: 'SPACE_UPDATE_SETTINGS',
  STYLE_ADD_SELECTOR: 'STYLE_ADD_SELECTOR',
  STYLE_UPDATE_SELECTOR: 'STYLE_UPDATE_SELECTOR',
  STYLE_REMOVE_SELECTOR: 'STYLE_REMOVE_SELECTOR',
  STYLE_ADD_VARIABLE: 'STYLE_ADD_VARIABLE',
  STYLE_UPDATE_VARIABLE: 'STYLE_UPDATE_VARIABLE',
  STYLE_REMOVE_VARIABLE: 'STYLE_REMOVE_VARIABLE',
  // Segments
  SEGMENT_ADD_ELEMENT: 'SEGMENT_ADD_ELEMENT',
  SEGMENT_UPDATE_ELEMENT: 'SEGMENT_UPDATE_ELEMENT',
  SEGMENT_REMOVE_ELEMENT: 'SEGMENT_REMOVE_ELEMENT',
  SEGMENT_MOVE_ELEMENT: 'SEGMENT_MOVE_ELEMENT',
  SEGMENT_CLONE_ELEMENT: 'SEGMENT_CLONE_ELEMENT',
  SEGMENT_ADD_TEMPLATE: 'SEGMENT_ADD_TEMPLATE',
  SEGMENT_STYLE_ADD_SELECTOR: 'SEGMENT_STYLE_ADD_SELECTOR',
  SEGMENT_STYLE_UPDATE_SELECTOR: 'SEGMENT_STYLE_UPDATE_SELECTOR',
  SEGMENT_STYLE_REMOVE_SELECTOR: 'SEGMENT_STYLE_REMOVE_SELECTOR',
  SEGMENT_STYLE_ADD_VARIABLE: 'SEGMENT_STYLE_ADD_VARIABLE',
  SEGMENT_STYLE_UPDATE_VARIABLE: 'SEGMENT_STYLE_UPDATE_VARIABLE',
  SEGMENT_STYLE_REMOVE_VARIABLE: 'SEGMENT_STYLE_REMOVE_VARIABLE'
};

export const SubscriptionEventTypesList = Object.keys(SubscriptionEventTypes);

// Subscription Events
export const RealTimeEventTypes = {
  INIT: 'INIT',
  KA: 'KA',
  MOUSE: 'MOUSE',
  ELEMENT: 'ELEMENT',
  COLLABORATOR_CONNECTED: 'COLLABORATOR_CONNECTED',
  COLLABORATOR_DISCONNECTED: 'COLLABORATOR_DISCONNECTED'
};

export const RealTimeEventTypesList = Object.keys(RealTimeEventTypes);

export const RealTimeSelfEventTypesList = [
  RealTimeEventTypes.COLLABORATOR_CONNECTED,
  RealTimeEventTypes.COLLABORATOR_DISCONNECTED
];
