import type { Style, StyleCategory, StyleValue } from '../types';

export const EMPTY_STYLE_SCHEMA: Style = {
  platform: { desktop: {}, tablet: {}, mobile: {} },
  mode: 'desktop-first',
  theme: {
    default: 'system',
    schemes: ['light', 'dark']
  },
  variables: {},
  cache: ''
};

const styleConstants = {
  // Display
  DISPLAY: 'display',
  FLEX_WRAP: 'flex-wrap',
  FLEX_DIRECTION: 'flex-direction',
  ALIGN_ITEMS: 'align-items',
  JUSTIFY_CONTENT: 'justify-content',
  ALIGN_CONTENT: 'align-content',
  ROW_GAP: 'row-gap',
  COLUMN_GAP: 'column-gap',
  GRID_ROW_GAP: 'grid-row-gap',
  GRID_COLUMN_GAP: 'grid-column-gap',
  GRID_TEMPLATE_AREAS: 'grid-template-areas',
  GRID_TEMPLATE_COLUMNS: 'grid-template-columns',
  GRID_TEMPLATE_ROWS: 'grid-template-rows',
  GRID_AUTO_FLOW: 'grid-auto-flow',
  GRID_AUTO_ROWS: 'grid-auto-rows',
  GRID_AUTO_COLUMNS: 'grid-auto-columns',
  // DisplayFlexChild
  ALIGN_SELF: 'align-self',
  ORDER: 'order',
  FLEX_GROW: 'flex-grow',
  FLEX_SHRINK: 'flex-shrink',
  FLEX_BASIS: 'flex-basis',
  // List
  LIST_STYLE: 'list-style',
  // ListItem
  LIST_STYLE_TYPE: 'list-style-type',
  // Background
  BACKGROUND_COLOR: 'background-color',
  BACKGROUND_IMAGE: 'background-image',
  BACKGROUND_POSITION: 'background-position',
  BACKGROUND_SIZE: 'background-size',
  BACKGROUND_REPEAT: 'background-repeat',
  BACKGROUND_CLIP: 'background-clip',
  BACKGROUND_ATTACHMENT: 'background-attachment',
  MASK_IMAGE: 'mask-image',
  // Border
  BORDER_TOP_STYLE: 'border-top-style',
  BORDER_TOP_WIDTH: 'border-top-width',
  BORDER_TOP_COLOR: 'border-top-color',
  BORDER_BOTTOM_STYLE: 'border-bottom-style',
  BORDER_BOTTOM_WIDTH: 'border-bottom-width',
  BORDER_BOTTOM_COLOR: 'border-bottom-color',
  BORDER_LEFT_STYLE: 'border-left-style',
  BORDER_LEFT_WIDTH: 'border-left-width',
  BORDER_LEFT_COLOR: 'border-left-color',
  BORDER_RIGHT_STYLE: 'border-right-style',
  BORDER_RIGHT_WIDTH: 'border-right-width',
  BORDER_RIGHT_COLOR: 'border-right-color',
  BORDER_TOP_LEFT_RADIUS: 'border-top-left-radius',
  BORDER_TOP_RIGHT_RADIUS: 'border-top-right-radius',
  BORDER_BOTTOM_LEFT_RADIUS: 'border-bottom-left-radius',
  BORDER_BOTTOM_RIGHT_RADIUS: 'border-bottom-right-radius',
  // Effects
  OPACITY: 'opacity',
  CURSOR: 'cursor',
  TRANSITION: 'transition',
  BOX_SHADOW: 'box-shadow',
  FILTER: 'filter',
  TRANSFORM: 'transform',
  // Position
  POSITION: 'position',
  FLOAT: 'float',
  CLEAR: 'clear',
  Z_INDEX: 'z-index',
  TOP: 'top',
  BOTTOM: 'bottom',
  LEFT: 'left',
  RIGHT: 'right',
  // Size
  WIDTH: 'width',
  HEIGHT: 'height',
  MIN_WIDTH: 'min-width',
  MIN_HEIGHT: 'min-height',
  MAX_WIDTH: 'max-width',
  MAX_HEIGHT: 'max-height',
  OVERFLOW: 'overflow',
  OBJECT_FIT: 'object-fit',
  OBJECT_POSITION: 'object-position',
  // Spacing
  MARGIN_TOP: 'margin-top',
  MARGIN_BOTTOM: 'margin-bottom',
  MARGIN_LEFT: 'margin-left',
  MARGIN_RIGHT: 'margin-right',
  PADDING_TOP: 'padding-top',
  PADDING_BOTTOM: 'padding-bottom',
  PADDING_LEFT: 'padding-left',
  PADDING_RIGHT: 'padding-right',
  // Typography
  FONT_FAMILY: 'font-family',
  FONT_WEIGHT: 'font-weight',
  FONT_SIZE: 'font-size',
  LINE_HEIGHT: 'line-height',
  COLOR: 'color',
  TEXT_ALIGN: 'text-align',
  FONT_STYLE: 'font-style',
  TEXT_DECORATION: 'text-decoration',
  LETTER_SPACING: 'letter-spacing',
  TEXT_INDENT: 'text-indent',
  TEXT_TRANSFORM: 'text-transform',
  DIRECTION: 'direction',
  WHITE_SPACE: 'white-space',
  TEXT_WRAP: 'text-wrap',
  TEXT_OVERFLOW: 'text-overflow',
  TEXT_SHADOW: 'text-shadow'
} as const;

export const inheritableAttributesBase: StyleCategory[] = [
  styleConstants.FONT_FAMILY,
  styleConstants.FONT_SIZE,
  styleConstants.FONT_STYLE,
  styleConstants.FONT_WEIGHT,
  styleConstants.COLOR,
  styleConstants.LINE_HEIGHT,
  styleConstants.LETTER_SPACING,
  styleConstants.TEXT_ALIGN,
  styleConstants.TEXT_DECORATION,
  styleConstants.TEXT_INDENT,
  styleConstants.TEXT_SHADOW,
  styleConstants.TEXT_TRANSFORM,
  styleConstants.TEXT_WRAP,
  styleConstants.TEXT_OVERFLOW,
  styleConstants.WHITE_SPACE,
  styleConstants.DIRECTION,
  styleConstants.CURSOR,
  styleConstants.LIST_STYLE,
  styleConstants.LIST_STYLE_TYPE
];

export const StyleBindingsAllowed = Object.values(styleConstants).map(attr => ({ path: attr, label: attr }));

export const baseDefaultValue: Record<StyleCategory, StyleValue> = {
  // display
  [styleConstants.DISPLAY]: 'block',
  [styleConstants.FLEX_WRAP]: 'nowrap',
  [styleConstants.FLEX_DIRECTION]: 'row',
  [styleConstants.ALIGN_ITEMS]: 'stretch',
  [styleConstants.JUSTIFY_CONTENT]: 'flex-start',
  [styleConstants.ALIGN_CONTENT]: 'flex-start',
  [styleConstants.ROW_GAP]: '0px',
  [styleConstants.COLUMN_GAP]: '0px',
  [styleConstants.GRID_ROW_GAP]: '0px',
  [styleConstants.GRID_COLUMN_GAP]: '0px',
  [styleConstants.GRID_TEMPLATE_AREAS]: 'none',
  [styleConstants.GRID_TEMPLATE_COLUMNS]: 'none',
  [styleConstants.GRID_TEMPLATE_ROWS]: 'none',
  [styleConstants.GRID_AUTO_FLOW]: 'row',
  [styleConstants.GRID_AUTO_ROWS]: 'auto',
  [styleConstants.GRID_AUTO_COLUMNS]: 'auto',
  // DisplayFlexChild
  [styleConstants.ALIGN_SELF]: 'auto',
  [styleConstants.ORDER]: '0',
  [styleConstants.FLEX_GROW]: '0',
  [styleConstants.FLEX_SHRINK]: '1',
  [styleConstants.FLEX_BASIS]: 'auto',
  // List
  [styleConstants.LIST_STYLE]: 'disc',
  // ListItem
  [styleConstants.LIST_STYLE_TYPE]: 'disc',
  // Background
  [styleConstants.BACKGROUND_COLOR]: 'transparent',
  [styleConstants.BACKGROUND_IMAGE]: 'url("https://cdn.plitzi.com/resources/img/background-image.svg")',
  [styleConstants.BACKGROUND_POSITION]: '0px 0px',
  [styleConstants.BACKGROUND_SIZE]: 'auto',
  [styleConstants.BACKGROUND_CLIP]: 'border-box',
  [styleConstants.BACKGROUND_REPEAT]: 'repeat',
  [styleConstants.BACKGROUND_ATTACHMENT]: 'scroll',
  [styleConstants.MASK_IMAGE]: 'none',
  // Border
  [styleConstants.BORDER_TOP_STYLE]: 'solid',
  [styleConstants.BORDER_TOP_WIDTH]: '0px',
  [styleConstants.BORDER_TOP_COLOR]: '#000000',
  [styleConstants.BORDER_BOTTOM_STYLE]: 'solid',
  [styleConstants.BORDER_BOTTOM_WIDTH]: '0px',
  [styleConstants.BORDER_BOTTOM_COLOR]: '#000000',
  [styleConstants.BORDER_LEFT_STYLE]: 'solid',
  [styleConstants.BORDER_LEFT_WIDTH]: '0px',
  [styleConstants.BORDER_LEFT_COLOR]: '#000000',
  [styleConstants.BORDER_RIGHT_STYLE]: 'solid',
  [styleConstants.BORDER_RIGHT_WIDTH]: '0px',
  [styleConstants.BORDER_RIGHT_COLOR]: '#000000',
  [styleConstants.BORDER_TOP_LEFT_RADIUS]: '0px',
  [styleConstants.BORDER_TOP_RIGHT_RADIUS]: '0px',
  [styleConstants.BORDER_BOTTOM_LEFT_RADIUS]: '0px',
  [styleConstants.BORDER_BOTTOM_RIGHT_RADIUS]: '0px',
  // Effects
  [styleConstants.OPACITY]: '1',
  [styleConstants.CURSOR]: 'auto',
  [styleConstants.TRANSITION]: 'opacity 200ms ease 0ms',
  [styleConstants.BOX_SHADOW]: '1px 1px 3px 1px black',
  [styleConstants.FILTER]: 'blur(5px)',
  [styleConstants.TRANSFORM]: 'translate3d(0px, 0px, 0px)',
  // Position
  [styleConstants.POSITION]: 'static',
  [styleConstants.FLOAT]: 'none',
  [styleConstants.CLEAR]: 'none',
  [styleConstants.Z_INDEX]: '0',
  [styleConstants.TOP]: 'auto',
  [styleConstants.BOTTOM]: 'auto',
  [styleConstants.LEFT]: 'auto',
  [styleConstants.RIGHT]: 'auto',
  // Size
  [styleConstants.WIDTH]: 'auto',
  [styleConstants.HEIGHT]: 'auto',
  [styleConstants.MIN_WIDTH]: '0px',
  [styleConstants.MIN_HEIGHT]: '0px',
  [styleConstants.MAX_WIDTH]: 'none',
  [styleConstants.MAX_HEIGHT]: 'none',
  [styleConstants.OVERFLOW]: 'visible',
  [styleConstants.OBJECT_FIT]: 'fill',
  [styleConstants.OBJECT_POSITION]: '50% 50%',
  // Spacing
  [styleConstants.MARGIN_TOP]: '0px',
  [styleConstants.MARGIN_BOTTOM]: '0px',
  [styleConstants.MARGIN_LEFT]: '0px',
  [styleConstants.MARGIN_RIGHT]: '0px',
  [styleConstants.PADDING_TOP]: '0px',
  [styleConstants.PADDING_BOTTOM]: '0px',
  [styleConstants.PADDING_LEFT]: '0px',
  [styleConstants.PADDING_RIGHT]: '0px',
  // Typography
  [styleConstants.FONT_FAMILY]: 'Arial',
  [styleConstants.FONT_WEIGHT]: 400,
  [styleConstants.FONT_SIZE]: '0px',
  [styleConstants.LINE_HEIGHT]: '0px',
  [styleConstants.COLOR]: '#000000',
  [styleConstants.TEXT_ALIGN]: 'left',
  [styleConstants.FONT_STYLE]: 'normal',
  [styleConstants.TEXT_DECORATION]: 'none',
  [styleConstants.LETTER_SPACING]: '0px',
  [styleConstants.TEXT_INDENT]: '0px',
  [styleConstants.TEXT_TRANSFORM]: 'none',
  [styleConstants.DIRECTION]: 'ltr',
  [styleConstants.WHITE_SPACE]: 'normal',
  [styleConstants.TEXT_WRAP]: 'wrap',
  [styleConstants.TEXT_OVERFLOW]: 'clip',
  [styleConstants.TEXT_SHADOW]: ''
};

export default styleConstants;
