import type { StyleValue } from '../types';

export enum StyleCategory {
  // Display
  DISPLAY = 'display',
  FLEX_WRAP = 'flex-wrap',
  FLEX_DIRECTION = 'flex-direction',
  ALIGN_ITEMS = 'align-items',
  JUSTIFY_CONTENT = 'justify-content',
  ALIGN_CONTENT = 'align-content',
  ROW_GAP = 'row-gap',
  COLUMN_GAP = 'column-gap',
  GRID_ROW_GAP = 'grid-row-gap',
  GRID_COLUMN_GAP = 'grid-column-gap',
  GRID_TEMPLATE_AREAS = 'grid-template-areas',
  GRID_TEMPLATE_COLUMNS = 'grid-template-columns',
  GRID_TEMPLATE_ROWS = 'grid-template-rows',
  GRID_AUTO_FLOW = 'grid-auto-flow',
  GRID_AUTO_ROWS = 'grid-auto-rows',
  GRID_AUTO_COLUMNS = 'grid-auto-columns',
  // DisplayFlexChild
  ALIGN_SELF = 'align-self',
  ORDER = 'order',
  FLEX_GROW = 'flex-grow',
  FLEX_SHRINK = 'flex-shrink',
  FLEX_BASIS = 'flex-basis',
  // List
  LIST_STYLE = 'list-style',
  // ListItem
  LIST_STYLE_TYPE = 'list-style-type',
  // Background
  BACKGROUND_COLOR = 'background-color',
  BACKGROUND_IMAGE = 'background-image',
  BACKGROUND_POSITION = 'background-position',
  BACKGROUND_SIZE = 'background-size',
  BACKGROUND_REPEAT = 'background-repeat',
  BACKGROUND_CLIP = 'background-clip',
  BACKGROUND_ATTACHMENT = 'background-attachment',
  MASK_IMAGE = 'mask-image',
  // Border
  BORDER_TOP_STYLE = 'border-top-style',
  BORDER_TOP_WIDTH = 'border-top-width',
  BORDER_TOP_COLOR = 'border-top-color',
  BORDER_BOTTOM_STYLE = 'border-bottom-style',
  BORDER_BOTTOM_WIDTH = 'border-bottom-width',
  BORDER_BOTTOM_COLOR = 'border-bottom-color',
  BORDER_LEFT_STYLE = 'border-left-style',
  BORDER_LEFT_WIDTH = 'border-left-width',
  BORDER_LEFT_COLOR = 'border-left-color',
  BORDER_RIGHT_STYLE = 'border-right-style',
  BORDER_RIGHT_WIDTH = 'border-right-width',
  BORDER_RIGHT_COLOR = 'border-right-color',
  BORDER_TOP_LEFT_RADIUS = 'border-top-left-radius',
  BORDER_TOP_RIGHT_RADIUS = 'border-top-right-radius',
  BORDER_BOTTOM_LEFT_RADIUS = 'border-bottom-left-radius',
  BORDER_BOTTOM_RIGHT_RADIUS = 'border-bottom-right-radius',
  // Effects
  OPACITY = 'opacity',
  CURSOR = 'cursor',
  TRANSITION = 'transition',
  BOX_SHADOW = 'box-shadow',
  FILTER = 'filter',
  TRANSFORM = 'transform',
  // Position
  POSITION = 'position',
  FLOAT = 'float',
  CLEAR = 'clear',
  Z_INDEX = 'z-index',
  TOP = 'top',
  BOTTOM = 'bottom',
  LEFT = 'left',
  RIGHT = 'right',
  // Size
  WIDTH = 'width',
  HEIGHT = 'height',
  MIN_WIDTH = 'min-width',
  MIN_HEIGHT = 'min-height',
  MAX_WIDTH = 'max-width',
  MAX_HEIGHT = 'max-height',
  OVERFLOW = 'overflow',
  OBJECT_FIT = 'object-fit',
  OBJECT_POSITION = 'object-position',
  // Spacing
  MARGIN_TOP = 'margin-top',
  MARGIN_BOTTOM = 'margin-bottom',
  MARGIN_LEFT = 'margin-left',
  MARGIN_RIGHT = 'margin-right',
  PADDING_TOP = 'padding-top',
  PADDING_BOTTOM = 'padding-bottom',
  PADDING_LEFT = 'padding-left',
  PADDING_RIGHT = 'padding-right',
  // Typography
  FONT_FAMILY = 'font-family',
  FONT_WEIGHT = 'font-weight',
  FONT_SIZE = 'font-size',
  LINE_HEIGHT = 'line-height',
  COLOR = 'color',
  TEXT_ALIGN = 'text-align',
  FONT_STYLE = 'font-style',
  TEXT_DECORATION = 'text-decoration',
  LETTER_SPACING = 'letter-spacing',
  TEXT_INDENT = 'text-indent',
  TEXT_TRANSFORM = 'text-transform',
  DIRECTION = 'direction',
  WHITE_SPACE = 'white-space',
  TEXT_WRAP = 'text-wrap',
  TEXT_OVERFLOW = 'text-overflow',
  TEXT_SHADOW = 'text-shadow'
}

export const inheritableAttributesBase = [
  StyleCategory.TEXT_DECORATION,
  StyleCategory.LINE_HEIGHT,
  StyleCategory.LETTER_SPACING,
  StyleCategory.COLOR,
  StyleCategory.DIRECTION,
  StyleCategory.FONT_FAMILY,
  StyleCategory.FONT_WEIGHT,
  StyleCategory.FONT_SIZE,
  StyleCategory.TEXT_ALIGN,
  StyleCategory.TEXT_INDENT,
  StyleCategory.TEXT_SHADOW,
  StyleCategory.TEXT_TRANSFORM,
  StyleCategory.WHITE_SPACE,
  StyleCategory.TEXT_WRAP,
  StyleCategory.TEXT_OVERFLOW
];

export const StyleBindingsAllowed = Object.values(StyleCategory).map(attr => ({ path: attr, label: attr }));

export const baseDefaultValue: Record<StyleCategory, StyleValue> = {
  // display
  [StyleCategory.DISPLAY]: 'block',
  [StyleCategory.FLEX_WRAP]: 'nowrap',
  [StyleCategory.FLEX_DIRECTION]: 'row',
  [StyleCategory.ALIGN_ITEMS]: 'stretch',
  [StyleCategory.JUSTIFY_CONTENT]: 'flex-start',
  [StyleCategory.ALIGN_CONTENT]: 'flex-start',
  [StyleCategory.ROW_GAP]: '0px',
  [StyleCategory.COLUMN_GAP]: '0px',
  [StyleCategory.GRID_ROW_GAP]: '0px',
  [StyleCategory.GRID_COLUMN_GAP]: '0px',
  [StyleCategory.GRID_TEMPLATE_AREAS]: 'none',
  [StyleCategory.GRID_TEMPLATE_COLUMNS]: 'none',
  [StyleCategory.GRID_TEMPLATE_ROWS]: 'none',
  [StyleCategory.GRID_AUTO_FLOW]: 'row',
  [StyleCategory.GRID_AUTO_ROWS]: 'auto',
  [StyleCategory.GRID_AUTO_COLUMNS]: 'auto',
  // DisplayFlexChild
  [StyleCategory.ALIGN_SELF]: 'auto',
  [StyleCategory.ORDER]: '0',
  [StyleCategory.FLEX_GROW]: '0',
  [StyleCategory.FLEX_SHRINK]: '1',
  [StyleCategory.FLEX_BASIS]: 'auto',
  // List
  [StyleCategory.LIST_STYLE]: 'disc',
  // ListItem
  [StyleCategory.LIST_STYLE_TYPE]: 'disc',
  // Background
  [StyleCategory.BACKGROUND_COLOR]: 'transparent',
  [StyleCategory.BACKGROUND_IMAGE]: 'url("https://cdn.plitzi.com/resources/img/background-image.svg")',
  [StyleCategory.BACKGROUND_POSITION]: '0px 0px',
  [StyleCategory.BACKGROUND_SIZE]: 'auto',
  [StyleCategory.BACKGROUND_CLIP]: 'border-box',
  [StyleCategory.BACKGROUND_REPEAT]: 'repeat',
  [StyleCategory.BACKGROUND_ATTACHMENT]: 'scroll',
  [StyleCategory.MASK_IMAGE]: 'none',
  // Border
  [StyleCategory.BORDER_TOP_STYLE]: 'solid',
  [StyleCategory.BORDER_TOP_WIDTH]: '0px',
  [StyleCategory.BORDER_TOP_COLOR]: '#000000',
  [StyleCategory.BORDER_BOTTOM_STYLE]: 'solid',
  [StyleCategory.BORDER_BOTTOM_WIDTH]: '0px',
  [StyleCategory.BORDER_BOTTOM_COLOR]: '#000000',
  [StyleCategory.BORDER_LEFT_STYLE]: 'solid',
  [StyleCategory.BORDER_LEFT_WIDTH]: '0px',
  [StyleCategory.BORDER_LEFT_COLOR]: '#000000',
  [StyleCategory.BORDER_RIGHT_STYLE]: 'solid',
  [StyleCategory.BORDER_RIGHT_WIDTH]: '0px',
  [StyleCategory.BORDER_RIGHT_COLOR]: '#000000',
  [StyleCategory.BORDER_TOP_LEFT_RADIUS]: '0px',
  [StyleCategory.BORDER_TOP_RIGHT_RADIUS]: '0px',
  [StyleCategory.BORDER_BOTTOM_LEFT_RADIUS]: '0px',
  [StyleCategory.BORDER_BOTTOM_RIGHT_RADIUS]: '0px',
  // Effects
  [StyleCategory.OPACITY]: '1',
  [StyleCategory.CURSOR]: 'auto',
  [StyleCategory.TRANSITION]: 'opacity 200ms ease 0ms',
  [StyleCategory.BOX_SHADOW]: '1px 1px 3px 1px black',
  [StyleCategory.FILTER]: 'blur(5px)',
  [StyleCategory.TRANSFORM]: 'translate3d(0px, 0px, 0px)',
  // Position
  [StyleCategory.POSITION]: 'static',
  [StyleCategory.FLOAT]: 'none',
  [StyleCategory.CLEAR]: 'none',
  [StyleCategory.Z_INDEX]: '0',
  [StyleCategory.TOP]: 'auto',
  [StyleCategory.BOTTOM]: 'auto',
  [StyleCategory.LEFT]: 'auto',
  [StyleCategory.RIGHT]: 'auto',
  // Size
  [StyleCategory.WIDTH]: 'auto',
  [StyleCategory.HEIGHT]: 'auto',
  [StyleCategory.MIN_WIDTH]: '0px',
  [StyleCategory.MIN_HEIGHT]: '0px',
  [StyleCategory.MAX_WIDTH]: 'none',
  [StyleCategory.MAX_HEIGHT]: 'none',
  [StyleCategory.OVERFLOW]: 'visible',
  [StyleCategory.OBJECT_FIT]: 'fill',
  [StyleCategory.OBJECT_POSITION]: '50% 50%',
  // Spacing
  [StyleCategory.MARGIN_TOP]: '0px',
  [StyleCategory.MARGIN_BOTTOM]: '0px',
  [StyleCategory.MARGIN_LEFT]: '0px',
  [StyleCategory.MARGIN_RIGHT]: '0px',
  [StyleCategory.PADDING_TOP]: '0px',
  [StyleCategory.PADDING_BOTTOM]: '0px',
  [StyleCategory.PADDING_LEFT]: '0px',
  [StyleCategory.PADDING_RIGHT]: '0px',
  // Typography
  [StyleCategory.FONT_FAMILY]: 'Arial',
  [StyleCategory.FONT_WEIGHT]: 400,
  [StyleCategory.FONT_SIZE]: '0px',
  [StyleCategory.LINE_HEIGHT]: '0px',
  [StyleCategory.COLOR]: '#000000',
  [StyleCategory.TEXT_ALIGN]: 'left',
  [StyleCategory.FONT_STYLE]: 'normal',
  [StyleCategory.TEXT_DECORATION]: 'none',
  [StyleCategory.LETTER_SPACING]: '0px',
  [StyleCategory.TEXT_INDENT]: '0px',
  [StyleCategory.TEXT_TRANSFORM]: 'none',
  [StyleCategory.DIRECTION]: 'ltr',
  [StyleCategory.WHITE_SPACE]: 'normal',
  [StyleCategory.TEXT_WRAP]: 'wrap',
  [StyleCategory.TEXT_OVERFLOW]: 'clip',
  [StyleCategory.TEXT_SHADOW]: ''
};
