/**
 * Writes `src/elements/attributeNames.ts`: the attributes each built-in element can be authored with, as data.
 *
 * The names exist only as TYPES — each element's `AuthorableAttributes<Props>` — and a type is gone by the time
 * anything runs. Reading a document back into code needs them at run time: an attribute no component reads is
 * dead weight a builder left behind, and writing it into a typed factory call is a compile error. So the compiler
 * reads them here, once, and `attributeNames.test.ts` fails the moment the data and the types disagree.
 *
 * Run from the package: `yarn generate:attribute-names`.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import ts from 'typescript';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const probePath = join(root, 'src', 'elements', '__attributeNamesProbe.ts');
const outPath = join(root, 'src', 'elements', 'attributeNames.ts');

const probe = `import type { elementDeclarations } from '@plitzi/sdk-elements/elements/declarations';
import type { AttributesOf } from '@plitzi/sdk-shared/authoring/declare';

export type Probe = {
  [Name in keyof typeof elementDeclarations as (typeof elementDeclarations)[Name]['type']]: AttributesOf<
    (typeof elementDeclarations)[Name]
  >;
};
`;

writeFileSync(probePath, probe);

try {
  const configPath = join(root, 'tsconfig.app.json');
  const config = ts.readConfigFile(configPath, path => ts.sys.readFile(path));
  const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, root);
  const program = ts.createProgram([probePath], { ...parsed.options, noEmit: true });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(probePath);
  if (!source) {
    throw new Error('The probe did not compile');
  }

  const alias = source.statements.find(ts.isTypeAliasDeclaration);
  if (!alias) {
    throw new Error('The probe declares no type');
  }

  const probeType = checker.getTypeAtLocation(alias.name);
  const entries = checker
    .getPropertiesOfType(probeType)
    .map(element => {
      const attributes = checker.getTypeOfSymbolAtLocation(element, alias);
      // An element whose attributes are an open record (a plugin host, a raw HTML node) accepts any name.
      const open = Boolean(checker.getIndexInfoOfType(attributes, ts.IndexKind.String));
      const names = checker
        .getPropertiesOfType(attributes)
        .map(property => property.getName())
        .sort((a, b) => a.localeCompare(b));

      return [element.getName(), open ? null : names] as const;
    })
    .sort(([a], [b]) => a.localeCompare(b));

  const lines = entries.map(
    ([type, names]) => `  ${type}: ${names === null ? 'null' : `[${names.map(name => `'${name}'`).join(', ')}]`}`
  );

  writeFileSync(
    outPath,
    `// Generated by scripts/generate-attribute-names.ts from each element's attribute TYPE — do not edit by hand.
// \`attributeNames.test.ts\` fails when this and the types disagree; regenerate with \`yarn generate:attribute-names\`.

/**
 * The attributes each built-in element can be authored with, by type — \`null\` for an element that takes any.
 *
 * What a component reads, and so what a document's attributes are allowed to say: anything else is left over from
 * a builder that has since moved on, and nothing renders it.
 */
export const elementAttributeNames = {
${lines.join(',\n')}
} as const satisfies Readonly<Record<string, readonly string[] | null>>;
`
  );
} finally {
  ts.sys.deleteFile?.(probePath);
}
