# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: ci

on:
  release:
    types: [published]
  push:
    branches:
      - develop
      - staging
      - main # Change this to your default branch

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: '@plitzi'
          cache: 'yarn'

      - name: Cache node_modules
        id: cache-packages
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn Token
        run: |
          yarn config set 'npmScopes["plitzi"]["npmAuthToken"]' "${{ secrets.NPM_AUTH_TOKEN }}"

      - name: Yarn Install
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: yarn install --immutable

  build-packages:
    needs: packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: '@plitzi'
          cache: 'yarn'

      - name: Restore Cache node_modules
        id: cache-packages
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Restore Cache build
        uses: actions/cache@v4
        env:
          cache-name: cache-build
        with:
          path: '**/dist'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-${{ github.sha }}

      - name: Yarn Build
        run: yarn build:prod && yarn build-vendor:dev && yarn build-vendor:prod

  lint:
    needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: '@plitzi'
          cache: 'yarn'

      - name: Restore Cache node_modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Restore Cache build
        id: cache-packages
        uses: actions/cache@v4
        env:
          cache-name: cache-build
        with:
          path: '**/dist'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-${{ github.sha }}

      - name: Validate Cache
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: exit 1

      - name: Yarn Lint
        run: yarn lint

      - name: Yarn Scss Lint
        run: yarn lint-style

      - name: Yarn Typecheck
        run: yarn typecheck

  # tests:
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  # - name: Enable Corepack
  # run: corepack enable

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 24
  #         registry-url: https://npm.pkg.github.com/plitzi
  # cache: 'yarn'

  #     - name: Restore Cache
  #       uses: actions/cache@v4
  #       env:
  #         cache-name: cache-node-modules
  #       with:
  #         path: '**/node_modules'
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

  #     - name: Yarn Tests
  #       run: yarn test:ci

  publish:
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - name: github
            url: https://npm.pkg.github.com
            token: NPM_AUTH_TOKEN
            scope: '@plitzi'
          - name: npm
            url: https://registry.npmjs.org
            token: NPMJS_TOKEN
            scope: '@plitzi'

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: ${{ matrix.registry.url }}
          scope: ${{ matrix.registry.scope }}
          cache: 'yarn'

      - name: Restore Cache node_modules
        id: cache-packages
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Restore Cache build
        id: cache-build
        uses: actions/cache@v4
        env:
          cache-name: cache-build
        with:
          path: '**/dist'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-${{ github.sha }}

      - name: Validate Cache
        if: steps.cache-packages.outputs.cache-hit != 'true' || steps.cache-build.outputs.cache-hit != 'true'
        run: exit 1

      - name: Yarn Token
        run: |
          yarn config set 'npmScopes["plitzi"]["npmRegistryServer"]' "${{ matrix.registry.url }}"
          yarn config set 'npmScopes["plitzi"]["npmAuthToken"]' "${{ secrets[matrix.registry.token] }}"

      - name: Publish packages
        uses: changesets/action@v1
        with:
          createGithubReleases: false
          publish: yarn ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets[matrix.registry.token] }}
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token] }}
          HOME: ${{ github.workspace }}
