# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: sdk_ci_deploy_s3

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to set latest'
        required: true
        default: ''

jobs:
  sync-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync s3://plitzi-cdn/sdk/${{ github.event.inputs.version }} s3://plitzi-cdn/sdk/latest --delete --cache-control max-age=300,public
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFROUND_DISTRIBUTION_ID }} --paths '/sdk/latest/*'
