import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Folders generated by bundlers or internal tooling that should not be exported
// Ignore configured folders (e.g. bundler virtual folders like _virtual created by Vite/Rolldown)
const IGNORED_DIRS = ['_virtual'];

const SOURCE_EXTENSIONS = ['.ts', '.tsx', '.js', '.jsx', '.mjs'];

function hasMeaningfulExports(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');

  // remove comments
  const cleaned = content
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\/\/.*$/gm, '')
    .trim();

  // should contain something exportable
  return (
    cleaned.includes('export') && cleaned.length > 0 && !/export\s*\{\s*\}/.test(cleaned) // export vacío
  );
}

/**
 * Whether a compiled module still has the source it was compiled from.
 *
 * `dist` is not emptied between development builds — rewriting every declaration file on each one is what kept the
 * editor re-indexing the whole workspace — so a module whose source was deleted stays on disk. Exporting it publishes
 * an entry point that a clean build, the one CI and every consumer's install get, does not have.
 *
 * @param {string} srcDir - The package's source folder
 * @param {string} relative - The module's path under dist, without extension
 * @returns {boolean}
 */
function hasSource(srcDir, relative) {
  const base = path.join(srcDir, relative);

  return SOURCE_EXTENSIONS.some(ext => fs.existsSync(`${base}${ext}`) || fs.existsSync(path.join(base, `index${ext}`)));
}

/**
 * Recursively scans the dist folder and generates exports
 *
 * @param {{ packageDir: string; distDir: string; srcDir: string }} dirs - Where the package, its build and its sources are
 * @param {string} dir - Current directory to scan
 * @param {string} prefix - Prefix for the export key
 * @returns {object} Exports object
 */
function scanExports(dirs, dir, prefix = '.') {
  const exportsObj = {};
  if (!fs.existsSync(dir)) {
    return exportsObj;
  }

  // Helper function to create a Node-compatible export path
  const makeExportPath = file => `./${path.relative(dirs.packageDir, file).replace(/\\/g, '/')}`;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory() && IGNORED_DIRS.includes(entry.name)) {
      continue;
    }

    // Key in exports, always starting with './'
    const key =
      prefix === '.' ? `./${entry.name.replace(/\.mjs$/, '')}` : `${prefix}/${entry.name.replace(/\.mjs$/, '')}`;
    const withSource = hasSource(dirs.srcDir, key.slice(2));

    if (entry.isDirectory()) {
      // For folders, check if index.mjs / index.cjs / index.d.ts exist
      const indexFiles = {
        types: path.join(entryPath, 'index.d.ts'),
        import: path.join(entryPath, 'index.mjs'),
        require: path.join(entryPath, 'index.cjs')
      };

      const exportEntry = {};
      // Only add paths that exist
      for (const [type, filePath] of Object.entries(indexFiles)) {
        if (fs.existsSync(filePath) && hasMeaningfulExports(filePath)) {
          exportEntry[type] = makeExportPath(filePath);
        }
      }

      if (
        withSource &&
        Object.keys(exportEntry).length &&
        (exportEntry.import || exportEntry.require) &&
        exportEntry.types
      ) {
        exportsObj[key] = exportEntry;
      }

      // Recursively scan subfolders
      Object.assign(exportsObj, scanExports(dirs, entryPath, key));
    } else if (withSource && entry.isFile() && entry.name.endsWith('.mjs')) {
      // For single .mjs files
      const files = {
        types: entryPath.replace(/\.mjs$/, '.d.ts'),
        import: entryPath,
        require: entryPath.replace(/\.mjs$/, '.cjs')
      };
      const exportEntry = {};
      for (const [type, filePath] of Object.entries(files)) {
        if (fs.existsSync(filePath) && hasMeaningfulExports(filePath)) {
          exportEntry[type] = makeExportPath(filePath);
        }
      }

      if (Object.keys(exportEntry).length) {
        exportsObj[key] = exportEntry;
      }
    }
  }

  return exportsObj;
}

/**
 * The `exports` map for a package: its main entry plus every compiled module that still has a source.
 *
 * @param {string} packageDir - The package root, holding `dist` and `src`
 * @returns {object} Exports object
 */
export function generateExports(packageDir) {
  const dirs = { packageDir, distDir: path.join(packageDir, 'dist'), srcDir: path.join(packageDir, 'src') };

  // Handle the main entry of the library (dist/index.*)
  const mainIndex = {
    types: path.join(dirs.distDir, 'index.d.ts'),
    import: path.join(dirs.distDir, 'index.mjs'),
    require: path.join(dirs.distDir, 'index.cjs')
  };
  const mainExports = {};
  for (const [type, file] of Object.entries(mainIndex)) {
    if (fs.existsSync(file)) {
      mainExports['.'] = { ...mainExports['.'], [type]: `./${path.relative(packageDir, file).replace(/\\/g, '/')}` };
    }
  }

  return { ...mainExports, ...scanExports(dirs, dirs.distDir) };
}

const invokedDirectly = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  const packageDir = process.cwd();
  const pkgPath = path.join(packageDir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));

  pkg.exports = generateExports(packageDir);
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

  console.log('✅ package.json updated with automatic exports for the entire library');
}
